// Sample news data for demo/development — shows what the feed looks like when populated

export const SAMPLE_NEWS = [
  {
    id: 'sample-001',
    title: 'OpenAI Launches GPT-5 with Real-Time Web Browsing and Multi-Modal Reasoning',
    link: 'https://openai.com/blog',
    source: 'OpenAI Blog',
    category: 'company',
    publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    summary: 'OpenAI has released GPT-5, featuring real-time web browsing, significantly improved reasoning capabilities, and native multi-modal understanding across text, images, and audio.',
    agentAngle: 'GPT-5\'s real-time web browsing means your AI assistant can now pull live MLS data, comp analysis, and neighborhood stats during client conversations. Agents who integrate this into their CRM workflow will answer client questions 10x faster than competitors still Googling.',
    implementationTip: 'Set up a GPT-5 custom assistant with your market area\'s MLS data feed. Use it to auto-generate property comparison reports — what used to take 30 minutes now takes 30 seconds.',
    trendingScore: 98,
  },
  {
    id: 'sample-002',
    title: 'Zillow Integrates AI-Powered Home Valuation That Predicts Prices 6 Months Out',
    link: 'https://www.housingwire.com',
    source: 'HousingWire',
    category: 'realestate',
    publishedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    summary: 'Zillow\'s new predictive pricing model uses 18 months of market data combined with local economic indicators to forecast home values 6 months ahead with 94% accuracy in test markets.',
    agentAngle: 'This is a double-edged sword. Sellers will come to you with Zillow\'s 6-month prediction printed out. You need to understand how the model works, where it fails (luxury, new construction, unique properties), and have your own data story ready. The agent who can explain WHY a prediction is off wins the listing.',
    implementationTip: 'Pull Zillow\'s prediction for your next 3 listing appointments. Prepare a side-by-side comparison with your CMA. Show sellers where AI gets it right AND wrong — positions you as the expert who goes deeper than algorithms.',
    trendingScore: 95,
  },
  {
    id: 'sample-003',
    title: 'Google Announces Gemini 3.0 with Native Real Estate Document Understanding',
    link: 'https://blog.google',
    source: 'Google AI Blog',
    category: 'company',
    publishedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    summary: 'Gemini 3.0 can read and analyze real estate contracts, inspection reports, and HOA documents natively, extracting key terms, red flags, and negotiation opportunities.',
    agentAngle: 'Imagine uploading a 200-page HOA doc and getting a 1-page summary of every rule your buyer needs to know — plus red flags about upcoming assessments or litigation. Agents who use this will deliver a level of due diligence that makes them indispensable.',
    implementationTip: 'Start with inspection reports. Upload your last 5 inspection reports to Gemini and ask it to categorize findings by severity and estimated repair cost. Build a template prompt you can reuse for every transaction.',
    trendingScore: 91,
  },
  {
    id: 'sample-004',
    title: 'Anthropic\'s Claude Can Now Generate Compliant Real Estate Marketing Copy',
    link: 'https://www.anthropic.com',
    source: 'Anthropic News',
    category: 'company',
    publishedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    summary: 'Anthropic has trained Claude on Fair Housing Act compliance, MLS listing rules, and state-specific real estate advertising regulations, making it the first AI that generates marketing copy agents can use directly.',
    agentAngle: 'This solves the #1 fear agents have about AI-generated content: compliance. No more worrying about accidentally saying "family-friendly neighborhood" or "walking distance to churches." Claude now flags and fixes Fair Housing violations before you post.',
    implementationTip: 'Use Claude to audit your existing listings and social media posts for compliance issues. Then set up a workflow: draft in your voice → Claude compliance check → post. Takes 2 minutes per listing.',
    trendingScore: 88,
  },
  {
    id: 'sample-005',
    title: 'Virtual Staging AI Now Indistinguishable from Professional Photography in Blind Tests',
    link: 'https://techcrunch.com',
    source: 'TechCrunch AI',
    category: 'tech',
    publishedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    summary: 'A Stanford study found that buyers could not distinguish between AI-staged and professionally photographed home interiors in 73% of cases, up from 41% just one year ago.',
    agentAngle: 'Virtual staging just crossed the uncanny valley. At $25-50 per room vs $2,000+ for physical staging, this is a game-changer for your listing budget. BUT — disclosure requirements vary by state. Get ahead of the ethics conversation before your board makes the rules for you.',
    implementationTip: 'Test 3 virtual staging tools this week: Apply Design AI, Virtual Staging AI, and Stager AI. Stage the same empty room with each and compare. Pick your winner and add it to every listing package.',
    trendingScore: 85,
  },
  {
    id: 'sample-006',
    title: 'NAR Report: Agents Using AI Tools Closing 23% More Transactions Than Non-Users',
    link: 'https://www.inman.com',
    source: 'Inman',
    category: 'realestate',
    publishedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    summary: 'The National Association of Realtors\' latest technology survey reveals that agents who regularly use AI tools in their business closed 23% more transactions and earned 31% higher GCI in 2025.',
    agentAngle: 'This is the stat you show your team to get buy-in on AI adoption. The gap is widening fast — agents who adopted AI early are pulling away. If you\'re not using AI tools daily, you\'re leaving money on the table. Period.',
    implementationTip: 'Share this stat in your next team meeting. Then pick ONE AI tool to adopt as a team this month. Start simple: an AI-powered CRM follow-up tool or automated market report generator.',
    trendingScore: 82,
  },
  {
    id: 'sample-007',
    title: 'Microsoft Copilot Gets Real Estate Plugin: Auto-Generates CMAs from MLS Data',
    link: 'https://www.theverge.com',
    source: 'The Verge AI',
    category: 'tech',
    publishedAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
    summary: 'Microsoft\'s Copilot now integrates with major MLS systems through a new real estate plugin, automatically pulling comp data and generating branded CMA reports in Word and PowerPoint.',
    agentAngle: 'If your brokerage uses Microsoft 365 (most do), you just got a free CMA generator. The catch: it\'s only as good as your MLS data feed. Agents who supplement with hyperlocal knowledge will still stand out.',
    trendingScore: 79,
  },
  {
    id: 'sample-008',
    title: 'AI-Powered Lead Scoring Now Predicts Seller Intent 4 Months Before Listing',
    link: 'https://venturebeat.com',
    source: 'VentureBeat AI',
    category: 'tech',
    publishedAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    summary: 'A new proptech startup claims its AI model can identify homeowners likely to sell within 4 months by analyzing public data signals including permit filings, mortgage data, and life event indicators.',
    agentAngle: 'Predictive seller targeting is the holy grail. If this works at scale, the agents who adopt it first will lock up listings before the homeowner even calls another agent. Watch this space closely.',
    trendingScore: 76,
  },
  {
    id: 'sample-009',
    title: 'ChatGPT\'s Voice Mode Being Used by Top Teams for After-Hours Lead Response',
    link: 'https://www.inman.com',
    source: 'Inman',
    category: 'realestate',
    publishedAt: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
    summary: 'Several top-producing teams are using ChatGPT\'s voice mode as a first-response system for after-hours leads, achieving 67% lead engagement rates vs 12% for traditional voicemail.',
    agentAngle: 'Speed to lead is everything. If a prospect calls at 10pm and gets an intelligent, conversational AI that can answer basic questions and book a showing, you\'ve already won. The teams doing this are converting leads that used to go to whoever answered first the next morning.',
    implementationTip: 'Set up a simple after-hours flow: missed call → AI voice responds with 3 questions (timeline, price range, preferred area) → books a callback. Test it with your own number first.',
    trendingScore: 73,
  },
  {
    id: 'sample-010',
    title: 'New Research: AI-Written Property Descriptions Get 34% More Clicks Than Human-Written',
    link: 'https://www.technologyreview.com',
    source: 'MIT Tech Review AI',
    category: 'research',
    publishedAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    summary: 'MIT researchers found that AI-optimized property descriptions, trained on click-through data from millions of listings, consistently outperform human-written descriptions in generating buyer interest.',
    agentAngle: 'Your listing descriptions are costing you clicks. AI doesn\'t just write faster — it writes what buyers actually want to read, based on data from millions of successful listings. The ego hit is real, but the numbers don\'t lie.',
    trendingScore: 70,
  },
];
